// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OnlineShop.Services.ProductAPI.Data;

#nullable disable

namespace Onlineshop.Services.ProductAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Onlineshop.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PictureUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<string>("ProductCategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Кружка ST градиент",
                            Name = "Кружка",
                            PictureUrl = "https://www.modi.ru/upload/resize_cache/product/3d8/250_273_240cd750bba9870f18aada2478b24840a/mm3ndp9890r7d40bck42bq6b4q0seugp.jpg",
                            Price = 299.0,
                            ProductCategoryName = "Посуда"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Тарелка 26 см",
                            Name = "Тарелка",
                            PictureUrl = "https://www.modi.ru/upload/resize_cache/product/b48/250_273_240cd750bba9870f18aada2478b24840a/4iihmyj7kflksk5a1gn8ax3vo21yu2z4.jpg",
                            Price = 159.0,
                            ProductCategoryName = "Посуда"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Стеклянная миска",
                            Name = "Миска",
                            PictureUrl = "https://www.modi.ru/upload/resize_cache/product/3ee/250_273_240cd750bba9870f18aada2478b24840a/3ee3caeebbef1bff678806669d533334.jpg",
                            Price = 450.0,
                            ProductCategoryName = "Посуда"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Стакан 380мл",
                            Name = "Стакан",
                            PictureUrl = "https://www.modi.ru/upload/resize_cache/product/c48/250_273_240cd750bba9870f18aada2478b24840a/2ujxde7jjrzhnxuywe19736f01ysw1j0.jpg",
                            Price = 370.0,
                            ProductCategoryName = "Посуда"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Банка с бамбуковой крышкой 900мл",
                            Name = "Банка",
                            PictureUrl = "https://www.modi.ru/upload/resize_cache/product/acd/250_273_240cd750bba9870f18aada2478b24840a/fp2o38xhuvzz8e8wrc1l2fkyx7wj0y0d.jpg",
                            Price = 630.0,
                            ProductCategoryName = "Посуда"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Миска 12х6см",
                            Name = "Миска",
                            PictureUrl = "https://www.modi.ru/upload/resize_cache/product/5bc/250_273_240cd750bba9870f18aada2478b24840a/wmkaby02mwvg07yo9duc6et4t46ugenh.jpg",
                            Price = 420.0,
                            ProductCategoryName = "Посуда"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
